#!/usr/bin/bash
# Author: https://github.com/mohabaks
# Description: quick script to install needed apps from fedora-<RELEASE_NO>-minimal templates
set -x
msg(){
 echo -e "[+]\033 [32m$@\033[0m"
}

packages_install(){
msg Doing system updates
dnf update -y
msg Installing packages
dnf install -y \
	adwaita-gtk2-theme \
	dbus-x11 \
	dunst \
	fuse \
	gimp \
	gnome-keyring \
	keepassxc \
	less \
	libreoffice \
	lyx \
	pipewire-qubes \
	polkit \
	psmisc \
	python3-pylatex \
	qt5-qtstyleplugins \
	qubes-app-shutdown-idle \
	qubes-core-agent-networking \
	qubes-core-agent-passwordless-root \
	qubes-core-agent-thunar \
	qubes-gpg-split \
	qubes-img-converter \
	qubes-pdf-converter \
	qubes-snapd-helper \
	tar \
	texlive-scheme-basic \
	texmaker
	'tex(beamer.cls)' \
	'tex(moderncv.cls)' \
	thunar-archive-plugin \
	thunar-media-tags-plugin \
	thunar-volman \
	thunderbird \
	thunderbird-qubes \
	tumbler \
	tumbler-extras \
	weechat \
	wget \
	zathura \
	zathura-pdf-mupdf
	

export http_proxy="http://127.0.0.1:8082/"
export https_proxy="http://127.0.0.1:8082/"
cd /tmp

msg Installing slack-desktop
slack_release="4.39.88"
slack_pkg="slack-${slack_release}-0.1.el8.x86_64.rpm"
wget -c https://downloads.slack-edge.com/desktop-releases/linux/x64/${slack_release}/${slack_pkg}
dnf install -y ${slack_pkg}
}

look_and_feel(){
	local WORK_DIR="/home/user/QubesIncoming/dom0"
	msg Copying confs, icons, and fonts
	cp -rf ${WORK_DIR}/.fonts/* /usr/share/fonts/
	cp -rf ${WORK_DIR}/.themes/* /usr/share/themes/
	cp -rf ${WORK_DIR}/Flat-Remix-Blue-Dark /usr/share/icons/
        cp -rf ${WORK_DIR}/material_cursors /usr/share/icons/
	cp -rf ${WORK_DIR}/conf/dunstrc /etc/xdg/dunst/dunstrc
	cp ${WORK_DIR}/conf/Trolltech.conf /etc/xdg/Trolltech.conf
	echo -e "QT_QPA_PLATFORMTHEME=gtk2\nGSK_RENDERER=cairo\nLIBGL_ALWAYS_SOFTWARE=1"|tee /etc/environment

	mkdir -p /etc/dconf/db/qubes.d
	mkdir -p /etc/gtk-3.0
	mkdir -p /etc/gtk-2.0

	cp -rf ${WORK_DIR}/conf/10-global-theme-settings /etc/dconf/db/qubes.d/
	cp -rf ${WORK_DIR}/conf/dconf_user_profile /etc/dconf/profile/user
	dconf update
	
	cp ${WORK_DIR}/conf/gtkrc-2.0 /etc/gtk-2.0/gtkrc
	cp ${WORK_DIR}/conf/settings.ini /etc/gtk-3.0/settings.ini
	cp -rf ${WORK_DIR}/.themes/* /usr/share/themes/

}

copy_binaries(){
	local WORK_DIR="/home/user/QubesIncoming/dom0"
	msg Copying binaries
	cp ${WORK_DIR}/bin/* /usr/bin/
	cp ${WORK_DIR}/conf/*.desktop /usr/share/applications/
}

cleanup(){
	local TARGET_DIR="/home/user/QubesIncoming"
	msg Doing cleanup for $TARGET_DIR
	rm -rf $TARGET_DIR
	rm -rf /tmp/*
}

# main
packages_install
look_and_feel
copy_binaries
cleanup
