#!/usr/bin/python

import imaplib

from os import sys

email = sys.argv[1]
password = sys.argv[2]

try:
    obj = imaplib.IMAP4_SSL('imap.gmail.com', 993)
    obj.login(email, password)
    obj.select()
    mail_no = len(obj.search(None, 'UnSeen')[1][0].split())
    if mail_no == 0:
        print("0")
    else:
        print("{}".format(mail_no))
except Exception as e:
    pass
