#!/bin/bash
# Description: quick script to fetch bitcoin price
if qvm-run --pass-io sys-net 'ping -c1 8.8.8.8' &>/dev/null;then
	price=$(qvm-run --pass-io sys-net 'curl -s https://blockchain.info/q/24hrprice')
	echo -n "$price"
fi
