#!/bin/bash
sxhkd &
pkill -9 polybar;polybar -q -c $HOME/.config/polybar/config.ini &
nitrogen --restore &
pkill -9 picom;picom --config $HOME/.config/picom/picom.conf -b &
$HOME/.config/bspwm/qubes-xdg-autostart &
dunst &
pkill -9 qui-clipboard; qui-clipboard &
pkill -9 qui-devices;qui-devices &
pkill -9 qui-disk-space;qui-disk-space &
pkill -9 qui-domains;qui-domains &
pkill -9 qui-updates;qui-updates &
