#!/usr/bin/sh
COLOR="#282828"

#
#  Global Settings
#

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          40

bspc config normal_border_color  "$COLOR"
bspc config focused_border_color "$COLOR"
bspc config urgent_border_color  "$COLOR"
bspc config presel_border_color  "$COLOR"

#
#  Rule Settings
#

bspc rule -a Lxappearance state=floating focus=on
bspc rule -a Pavucontrol state=floating focus=on
bspc rule -a Qubes-update-gui state=floating focus=on
bspc rule -a Nitrogen state=floating focus=on

#
# Autostart apps
#

$HOME/.config/bspwm/autostart
