#!/usr/local/bin/bash

image="$HOME/Pictures/Walls/MON/01.png"

lockscreen(){

        exec swaylock -i "$image" \
	     --ring-color=00000000 \
	     --key-hl-color=ebdbb2 \
	     --bs-hl-color=ebdbb2 \
	     --text-color=ebdbb2 \
	     --font "Monofur Nerd Font" \
	     --indicator-idle-visible \
	     --line-color=00000000 \
	     --font-size 11 \
	     --inside-color 11080808 &
}

lockscreen 
