#!/bin/bash

# This script will randomly go through the files of a directory, setting it
# up as the wallpaper at regular intervals
#
# NOTE: this script is in bash (not posix shell), because the RANDOM variable
# we use is not defined in posix

#if [[ $# -lt 1 ]] || [[ ! -d $1   ]]; then
#	echo "Usage:
#	$0 <dir containing images>"
#	exit 1
#fi

# initilize the daemon
if pgrep swww-daemon;then
	pkill -9 swww-daemon
fi

swww init

if `xrandr -q | grep -q "HDMI-A-1 connected"`
then
        dir="$HOME/Pictures/Walls/MON/"
else
        dir="$HOME/Pictures/Walls/LAP/"
fi

# Edit below to control the images transition
#export SWWW_TRANSITION_FPS=60
#export SWWW_TRANSITION_STEP=2

# This controls (in seconds) when to switch to the next image
INTERVAL=300

while true; do
	find "$dir" \
		| while read -r img; do
			echo "$((RANDOM % 1000)):$img"
		done \
		| sort -n | cut -d':' -f2- \
		| while read -r img; do
			swww img  -t outer "$img"
			sleep $INTERVAL
		done
done &
